eventosbrasilia/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :eventos do
        resources :reviews, except: [:show, :index]
  end
  get 'pages/sobre'

  get 'pages/contato'

  root 'eventos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventosbrasilia/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventosbrasilia/app/models/evento.rb
class Evento < ApplicationRecord
	mount_uploader :image, ImageUploader

	has_many :reviews
end

eventosbrasilia/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :evento
end

eventosbrasilia/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy
end

eventosbrasilia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

eventosbrasilia/app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
      @reviews = Review.where(evento_id: @evento.id)
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:name, :address, :data, :hour, :website, :image)
    end
end

eventosbrasilia/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def sobre
  end

  def contato
  end
end

eventosbrasilia/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_evento
  before_action :authenticate_user!

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.evento_id = @evento.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @evento, notice: 'Review foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_evento
      @evento = Evento.find(params[:evento_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

eventosbrasilia/app/helpers/application_helper.rb
module ApplicationHelper
end

eventosbrasilia/app/helpers/eventos_helper.rb
module EventosHelper
end

eventosbrasilia/app/helpers/pages_helper.rb
module PagesHelper
end

eventosbrasilia/app/helpers/reviews_helper.rb
module ReviewsHelper
end

eventosbrasilia/app/views/eventos/_form.html.erb
<%= form_for(@evento, :html => { multipart: true}) do |f| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :hour %>
    <%= f.text_field :hour, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :data %>
    <%= f.text_field :data, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

eventosbrasilia/app/views/eventos/edit.html.erb
<h1>Editando Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Mostrar', @evento, class: "btn btn-link" %> |
<%= link_to 'Voltar', eventos_path, class: "btn btn-link" %>

eventosbrasilia/app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="fb-login-button" data-max-rows="1" data-size="medium" data-show-faces="true" data-auto-logout-link="true"></div>
<br>
<div class="jumbotron">
    <h2>EventosBrasilia é a melhor forma de saber o que está acontecendo perto de você!</h2>
</div>

<%= link_to 'Novo Evento', new_evento_path, class: "btn btn-primary" %>

<h1>Eventos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Evento</th>
      <th>Endereco</th>
      <th>Hora</th>
      <th>Data</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.name %></td>
        <td><%= evento.address %></td>
        <td><%= evento.hour %></td>
        <td><%= evento.data %></td>
        <td><%= link_to evento.website, evento.website %></td>
        <td><%= link_to 'Mostrar', evento, class: "btn btn-link" %></td>
        <td><%= link_to 'Editar', edit_evento_path(evento), class: "btn btn-link" %></td>
        <td><%= link_to 'Excluir', evento, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class= "center">
    <div class="fb-like" data-href="https://eventosbrasilia.herokuapp.com" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
</div>

eventosbrasilia/app/views/eventos/new.html.erb
<h1>Novo Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Voltar', eventos_path, class: "btn btn-link" %>

eventosbrasilia/app/views/eventos/show.html.erb
<div class="row">
    <div class="col-md-3">
            <%= image_tag @evento.image_url %>
            <br>
            <br>
      <h2>
          <%= @evento.name %>
      </h2>

        <p>
          <strong>Address:</strong>
          <%= @evento.address %>
        </p>

        <p>
          <strong>Hour:</strong>
          <%= @evento.hour %>
        </p>

        <p>
          <strong>Data:</strong>
          <%= @evento.data %>
        </p>

        <p>
          <strong>Website:</strong>
          <%=link_to @evento.website, @evento.website %>
        </p>
        <br>

        <%= link_to "Escreva um Review", new_evento_review_path(@evento), class: "btn btn-primary" %>

    </div>

    <div class="col-md-9">
        <% if @reviews.blank? %>
        <h3> Nenhum comentário ainda, seja o primeiro a escrever um! </h3>
        <% else %>
        <% @reviews.each do |review| %>
            <p><%= review.rating %></p>
            <p><%= review.comment %></p>
        <% end %>
        <% end %>
    </div>
</div>


<br>

<iframe
  width="270"
  height="270"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAROf48HPiVTYhJj2XqghJvNyTUmQ90PPM
    &q=<%= @evento.address.parameterize %>" allowfullscreen>
</iframe>
<br>
<br>
<%= link_to 'Editar', edit_evento_path(@evento), class: "btn btn-link" %> |
<%= link_to 'Voltar', eventos_path, class: "btn btn-link" %>

eventosbrasilia/app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

eventosbrasilia/app/views/layouts/_facebooklike.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=1111417615643486";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

eventosbrasilia/app/views/layouts/_facebooklogin.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=1111417615643486";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

eventosbrasilia/app/views/layouts/_facebooksend.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=1111417615643486";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

eventosbrasilia/app/views/layouts/_footer.html.erb
<p>Copyright Gabriel Ziegler & Daniel Oda</p>

eventosbrasilia/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<%= link_to "EventosBrasilia", root_path, class: "navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
          <li><%= link_to "Sobre", pages_sobre_path %></li>
          <li><%= link_to "Contato", pages_contato_path %></li>

          <% if user_signed_in? %>
              <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
              <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Inscrever-se", new_user_registration_path %></li>
              <li><%= link_to "Iniciar sessão", new_user_session_path %></li>
          <% end %>
        </ul>
        <!-- <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <!-- <button type="submit" class="btn btn-default">Submit</button> -->
        </form
        
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

eventosbrasilia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <%= render 'layouts/facebooklogin' %>
    <title>Eventosbrasilia</title>
            <%= csrf_meta_tags %>

            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
            <%= render 'layouts/bootstrap' %>
    </head>
  <body>
      <br>
      <%= render 'layouts/facebooklike' %>
            <%= render 'layouts/navbar' %>
                <div class="container-fluid">
                        <% flash.each do |name, msg| %>
                        <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class=
                        "sr-only">Close</spar></button>
                        <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
          <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

eventosbrasilia/app/views/pages/contato.html.erb
<h1>Nós adorariamos ouvir de você!</h1>
<h2>Ajude-nos a melhorar nossa aplicacão!</h2>
<h3>Envie emails com sugestões para:</h3>
<p>gabrielziegler55@gmail.com</p>

eventosbrasilia/app/views/pages/sobre.html.erb
<h1>Esta é uma aplicacão desenvolvida por alunos de Engenharia de Software da UnB.</h1>
<h2>O website foi desenvolvido a partir de ferramentas do Ruby on Rails e de práticas de Orientacão a objetos.</h2>

eventosbrasilia/app/views/reviews/_form.html.erb
<%= form_for([@evento, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :rating, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

eventosbrasilia/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Mostrar', '#' %> |
<%= link_to 'Voltar', evento_path(@evento) %>

eventosbrasilia/app/views/reviews/new.html.erb
<h1>Novo Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Voltar', evento_path(@evento) %>